pipeline {
    agent { docker 'node:9.4.0' }
    stages {
        stage('build') {
            steps {
                sh 'npm --version'
                sh 'echo "Hello world!"'
            }
        }
    }
}
